### ISSUE TITLE
Issue with encode/decode for kraken2-multiple.py

### ISSUE THREAD

**Issue by mchish** [npbhavya/Kraken2-output-manipulation#1]
When I run your kraken-multiple.py from my command line  I get the following error:
<img width="686" alt="Screen Shot 2020-06-20 at 9 22 38 PM" src="https://user-images.githubusercontent.com/67133512/85214684-7c1e6d80-b33c-11ea-813e-0783716d638b.png">

Do you know how I can resolve this? When I run it using ascii instead of utf-8 I get a similar error saying it can't decode

**Comment by npbhavya** [comment]
Can you open python3 and run the below commands to confirm the default is set to 'utf-8'. 
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'

I have been running this command on a  bash shell, with python v3.6.8 and CentOS. Are you running this command on Windows?

Can you check the files in the bracken_500_y directory to confirm the encoding format of these files is utf-8.

**Comment by mchish** [comment]
> Can you open python3 and run the below commands to confirm the default is set to 'utf-8'.
> 
> > > > import sys
> > > > sys.getdefaultencoding()
> > > > 'utf-8'
> 
> I have been running this command on a bash shell, with python v3.6.8 and CentOS. Are you running this command on Windows?
> 
> Can you check the files in the bracken_500_y directory to confirm the encoding format of these files is utf-8.

Hi! My python is running utf-8 . I'm running from the terminal with the same python version on a macos catalina version 10.15 and it does look like the encoding format on the files in my bracken directory are encoded with asci-ii. Do you have any recs on how I can fix this? (esp fixing it from the command line )

**Comment by npbhavya** [comment]
I havent done this before, but maybe you can try the iconv command, here is a tutorial I found https://www.tecmint.com/convert-files-to-utf-8-encoding-in-linux/

**Comment by eparisis** [comment]
Hi there! 

Im having the exact same problem as @mchish. My files seem to also be encoded in us-ascii and I've tried iconv to convert the KReport files to utf-8 or ISO-8859-1 (found this [here](https://stackoverflow.com/questions/42339876/error-unicodedecodeerror-utf-8-codec-cant-decode-byte-0xff-in-position-0-in)) but doesn't work.

utf-8 is my defaultencoding in python and I'm running Python 3.9.9 through the mac terminal on macOS Monterey.

Did you find any solutions for this?
Thanks!

**Comment by npbhavya** [comment]
Hi, 

In the script, change the line "kraken-multiple.py" or "kraken-multiple-taxa.py ", change the line 
"openfi=open(file, 'r')"
to
"openfi=open(file, 'rb')"
 Save this change and try running the script again. Let me know if fixes the encoding decoding error.
