### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by marce-sarrias** [npbhavya/Kraken2-output-manipulation#5]
Hi,

I'm trying to run the following command: 

python3 ./kraken-multiple-taxa.py -d ${Dir} -r F -c 2 -o ${Dir}/kraken-report-final-family

but I get this error:

Traceback (most recent call last):
  File "./kraken-multiple-taxa.py", line 60, in <module>
    kraken_cat_report(results.directory, results.rank, results.column, results.output)
  File "./kraken-multiple-taxa.py", line 17, in kraken_cat_report
    filelist=input_dir(dir)
  File "./kraken-multiple-taxa.py", line 44, in input_dir
    fields=line.split('\t')
TypeError: a bytes-like object is required, not 'str'

(as a reference, I used kraken2 2.0.9 and python3)

I'm not sure what this error means. Could you please help me out?! 

Thanks!

Marcela

**Comment by marce-sarrias** [comment]
Hi,

I fixed this issue by changing  'rb' to 'r' in lines openfi=open(file, 'r') and report=open(fipath, 'r').

Marcela

**Comment by npbhavya** [comment]
Thank you for pointing this out and the fix. Updated the scripts from 'rb' to 'r'.

**Comment by npbhavya** [comment]
Closing since its been fixed
